<a href="https://colab.research.google.com/github/tanvighorpade/edaexample/blob/main/Data_cleaning_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("my_file (1).csv")

In [6]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      object
 2   All Time Peak                     6 non-null      object
 3   Actual gross                      20 non-null     object
 4   Adjusted gross (in 2022 dollars)  20 non-null     object
 5   Artist                            20 non-null     object
 6   Tour title                        20 non-null     object
 7   Year(s)                           20 non-null     object
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     object
 10  Ref.                              20 non-null     object
dtypes: int64(2), object(9)
memory usage: 1.8+ KB

In [8]:
df.shape

(20, 11)

In [11]:
df.tail

<bound method NDFrame.tail of     Rank   Peak All Time Peak     Actual gross  \
0      1      1             2     $780,000,000
1      2      1          7[2]     $579,800,000
2      3   1[4]          2[5]     $411,000,000
3      4   2[7]         10[7]     $397,300,000
4      5   2[4]           NaN     $345,675,146
5      6   2[4]         10[9]     $305,158,363
6      7  2[10]           NaN     $280,000,000
7      7    NaN           NaN     $257,600,000
8      9    NaN           NaN     $256,084,556
9     10    NaN           NaN     $250,400,000
10    11    NaN           NaN  $229,100,000[b]
11    12    NaN        14[17]     $227,400,000
12    13    NaN           NaN     $204,000,000
13    14  1[20]           NaN     $200,000,000
14    15   2[c]           NaN     $194,000,000
15    16    NaN           NaN     $184,000,000
16    17    NaN           NaN     $170,000,000
17    18    NaN           NaN     $169,800,000
18    19    NaN           NaN  $167,700,000[e]
19    20    NaN           NaN     $150,000,000

   Adjusted gross (in 2022 dollars)        Artist  \
0                      $780,000,000  Taylor Swift
1                      $579,800,000       Beyoncé
2                      $560,622,615       Madonna
3                      $454,751,555          Pink
4                      $402,844,849  Taylor Swift
5                      $388,978,496       Madonna
6                      $381,932,682   Celine Dion
7                      $257,600,000          Pink
8                      $312,258,401       Beyoncé
9                      $309,141,878  Taylor Swift
10                     $283,202,896       Beyoncé
11                     $295,301,479     Lady Gaga
12                     $251,856,802    Katy Perry
13                     $299,676,265          Cher
14                     $281,617,035       Madonna
15                     $227,452,347          Pink
16                     $213,568,571     Lady Gaga
17                     $207,046,755       Madonna
18                     $204,486,106         Adele
19                     $185,423,109  Taylor Swift

                                  Tour title    Year(s)  Shows Average gross  \
0                            The Eras Tour †  2023–2024     56   $13,928,571
1                     Renaissance World Tour       2023     56   $10,353,571
2                Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3                Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4                    Reputation Stadium Tour       2018     53    $6,522,173
5                              The MDNA Tour       2012     88    $3,467,709
6                  Taking Chances World Tour  2008–2009    131    $2,137,405
7                          Summer Carnival †  2023–2024     41    $6,282,927
8                   The Formation World Tour       2016     49    $5,226,215
9                        The 1989 World Tour       2015     85    $2,945,882
10           The Mrs. Carter Show World Tour  2013–2014    132    $1,735,606
11                   The Monster Ball Tour *  2009–2011    203    $1,118,227
12                      Prismatic World Tour  2014–2015    151    $1,350,993
13  Living Proof: The Farewell Tour ‡[21][a]  2002–2005    325      $615,385
14                          Confessions Tour       2006     60    $3,233,333
15                 The Truth About Love Tour  2013–2014    142    $1,295,775
16                        Born This Way Ball  2012–2013     98    $1,734,694
17                          Rebel Heart Tour  2015–2016     82    $2,070,732
18                           Adele Live 2016  2016–2017    121    $1,385,950
19                              The Red Tour  2013–2014     86    $1,744,186

        Ref.
0        [1]
1        [3]
2        [6]
3        [7]
4        [8]
5        [9]
6       [11]
7       [12]
8       [13]
9       [14]
10  [15][16]
11      [18]
12      [19]
13      [20]
14       [5]
15      [22]
16       [d]
17       [4]
18      [25]
19      [26]  >

In [10]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [18]:
df["Peak"]=pd.to_numeric(df["Peak"],errors="coerce")
df["All Time Peak"] = df["All Time Peak"].astype(str).str.replace(r'\[.*?\]', '', regex=True)
df["All Time Peak"] = pd.to_numeric(df["All Time Peak"], errors="coerce")
df["All Time Peak"].fillna(df["All Time Peak"].mean(), inplace=True)

In [19]:
df["Peak"]

0     1.0
1     1.0
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
Name: Peak, dtype: float64

In [21]:
df["Peak"].fillna(np.mean(df["Peak"]))

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
Name: Peak, dtype: float64

In [22]:
df["Peak"]

0     1.0
1     1.0
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
Name: Peak, dtype: float64

In [24]:
df["Peak"].fillna(np.mean(df["Peak"]),inplace=True)

In [25]:
df.isnull

<bound method DataFrame.isnull of     Rank  Peak All Time Peak     Actual gross  \
0      1   1.0             2     $780,000,000
1      2   1.0          7[2]     $579,800,000
2      3   1.0          2[5]     $411,000,000
3      4   1.0         10[7]     $397,300,000
4      5   1.0           NaN     $345,675,146
5      6   1.0         10[9]     $305,158,363
6      7   1.0           NaN     $280,000,000
7      7   1.0           NaN     $257,600,000
8      9   1.0           NaN     $256,084,556
9     10   1.0           NaN     $250,400,000
10    11   1.0           NaN  $229,100,000[b]
11    12   1.0        14[17]     $227,400,000
12    13   1.0           NaN     $204,000,000
13    14   1.0           NaN     $200,000,000
14    15   1.0           NaN     $194,000,000
15    16   1.0           NaN     $184,000,000
16    17   1.0           NaN     $170,000,000
17    18   1.0           NaN     $169,800,000
18    19   1.0           NaN  $167,700,000[e]
19    20   1.0           NaN     $150,000,000

   Adjusted gross (in 2022 dollars)        Artist  \
0                      $780,000,000  Taylor Swift
1                      $579,800,000       Beyoncé
2                      $560,622,615       Madonna
3                      $454,751,555          Pink
4                      $402,844,849  Taylor Swift
5                      $388,978,496       Madonna
6                      $381,932,682   Celine Dion
7                      $257,600,000          Pink
8                      $312,258,401       Beyoncé
9                      $309,141,878  Taylor Swift
10                     $283,202,896       Beyoncé
11                     $295,301,479     Lady Gaga
12                     $251,856,802    Katy Perry
13                     $299,676,265          Cher
14                     $281,617,035       Madonna
15                     $227,452,347          Pink
16                     $213,568,571     Lady Gaga
17                     $207,046,755       Madonna
18                     $204,486,106         Adele
19                     $185,423,109  Taylor Swift

                                  Tour title    Year(s)  Shows Average gross  \
0                            The Eras Tour †  2023–2024     56   $13,928,571
1                     Renaissance World Tour       2023     56   $10,353,571
2                Sticky & Sweet Tour ‡[4][a]  2008–2009     85    $4,835,294
3                Beautiful Trauma World Tour  2018–2019    156    $2,546,795
4                    Reputation Stadium Tour       2018     53    $6,522,173
5                              The MDNA Tour       2012     88    $3,467,709
6                  Taking Chances World Tour  2008–2009    131    $2,137,405
7                          Summer Carnival †  2023–2024     41    $6,282,927
8                   The Formation World Tour       2016     49    $5,226,215
9                        The 1989 World Tour       2015     85    $2,945,882
10           The Mrs. Carter Show World Tour  2013–2014    132    $1,735,606
11                   The Monster Ball Tour *  2009–2011    203    $1,118,227
12                      Prismatic World Tour  2014–2015    151    $1,350,993
13  Living Proof: The Farewell Tour ‡[21][a]  2002–2005    325      $615,385
14                          Confessions Tour       2006     60    $3,233,333
15                 The Truth About Love Tour  2013–2014    142    $1,295,775
16                        Born This Way Ball  2012–2013     98    $1,734,694
17                          Rebel Heart Tour  2015–2016     82    $2,070,732
18                           Adele Live 2016  2016–2017    121    $1,385,950
19                              The Red Tour  2013–2014     86    $1,744,186

        Ref.
0        [1]
1        [3]
2        [6]
3        [7]
4        [8]
5        [9]
6       [11]
7       [12]
8       [13]
9       [14]
10  [15][16]
11      [18]
12      [19]
13      [20]
14       [5]
15      [22]
16       [d]
17       [4]
18      [25]
19      [26]  >

In [26]:
df.drop_duplicates()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1.0,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1.0,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1.0,2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,1.0,10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,1.0,NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,1.0,10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,1.0,NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,1.0,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,1.0,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,1.0,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,1.0,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,1.0,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,1.0,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1.0,NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,1.0,NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,1.0,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,1.0,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,1.0,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,1.0,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,1.0,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [27]:
df.isnull().sum()

Rank                                 0
Peak                                 0
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [28]:
df.to_csv("cleaned.csv",index=False)